import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc, collection, writeBatch, serverTimestamp } from 'firebase/firestore';
import fs from 'fs';
const env = await initializeTestEnvironment({ projectId: 'demo-ms', firestore: { rules: fs.readFileSync('firestore.rules','utf8'), host:'127.0.0.1', port:8181 } });
const H = c => c.repeat(64);            // fake hashes
const K1=H('a'), K2=H('b'), KX=H('c'), KO=H('d');
const alice=env.authenticatedContext('alice').firestore(), bob=env.authenticatedContext('bob').firestore(), mal=env.authenticatedContext('mal').firestore(), anon=env.unauthenticatedContext().firestore();
let n=0, bad=0; const t=async(name,p,ok)=>{ n++; try{ await (ok?assertSucceeds(p):assertFails(p)); console.log('  ok  ',name);}catch(e){ bad++; console.log('  FAIL',name,e.message);} };
const createTeam=(db,uid,tid,key,name='Mustangs')=>{ const b=writeBatch(db);
  b.set(doc(db,'teams',tid),{name,pwVersion:1,createdAt:serverTimestamp()}); b.set(doc(db,'teamKeys',key),{teamId:tid,pwVersion:1}); b.set(doc(db,'teams',tid,'members',uid),{pwVersion:1,key}); return b.commit(); };
const ath=(uid,name='Maya L.',extra={})=>({name,group:'Varsity',updatedAt:serverTimestamp(),updatedBy:uid,...extra});

console.log('create');
await t('unauthenticated cannot create a team', createTeam(anon,'x','T0',KX), false);
await t('alice creates team T1', createTeam(alice,'alice','T1',K1), true);
await t('create with a taken password fails', createTeam(mal,'mal','T9',K1), false);
await t('create team without a key fails', (()=>{const b=writeBatch(mal); b.set(doc(mal,'teams','T8'),{name:'x',pwVersion:1,createdAt:serverTimestamp()}); b.set(doc(mal,'teams','T8','members','mal'),{pwVersion:1,key:KX}); return b.commit();})(), false);
console.log('privacy');
await t('mal cannot list teams', getDocs(collection(mal,'teams')), false);
await t('mal cannot list teamKeys', getDocs(collection(mal,'teamKeys')), false);
await t('mal cannot get team T1', getDoc(doc(mal,'teams','T1')), false);
await t('mal cannot read athletes', getDocs(collection(mal,'teams','T1','athletes')), false);
await t('mal cannot read alice membership', getDoc(doc(mal,'teams','T1','members','alice')), false);
await t('unauthenticated cannot get a key', getDoc(doc(anon,'teamKeys',K1)), false);
console.log('join');
await t('mal cannot join with a wrong key', setDoc(doc(mal,'teams','T1','members','mal'),{pwVersion:1,key:KX}), false);
await t('mal cannot forge a key for T1', setDoc(doc(mal,'teamKeys',KX),{teamId:'T1',pwVersion:1}), false);
await t('mal cannot forge a v2 key for T1', setDoc(doc(mal,'teamKeys',KX),{teamId:'T1',pwVersion:2}), false);
await t('mal cannot join as someone else', setDoc(doc(mal,'teams','T1','members','bob'),{pwVersion:1,key:K1}), false);
await t('bob gets key by hash', getDoc(doc(bob,'teamKeys',K1)), true);
await t('bob joins with the right key', setDoc(doc(bob,'teams','T1','members','bob'),{pwVersion:1,key:K1}), true);
await t('bob reads team', getDoc(doc(bob,'teams','T1')), true);
await t('membership with extra fields fails', setDoc(doc(bob,'teams','T1','members','bob'),{pwVersion:1,key:K1,role:'admin'}), false);
console.log('data');
await t('alice writes athlete', setDoc(doc(alice,'teams','T1','athletes','a1'),ath('alice')), true);
await t('bob reads athletes', getDocs(collection(bob,'teams','T1','athletes')), true);
await t('athlete name over 30 fails', setDoc(doc(alice,'teams','T1','athletes','a2'),ath('alice','x'.repeat(31))), false);
await t('athlete extra field fails', setDoc(doc(alice,'teams','T1','athletes','a2'),ath('alice','Jo',{phone:'555'})), false);
await t('athlete updatedBy spoof fails', setDoc(doc(alice,'teams','T1','athletes','a2'),ath('bob')), false);
await t('workout write', setDoc(doc(alice,'teams','T1','workouts','w1'),{name:'CV',reps:'5',rest:'1:30',restUnit:'mss',segments:[{id:'s',effort:'cv',dist:1000,mode:'per400',value:'1:28',cp:200}],updatedAt:serverTimestamp(),updatedBy:'alice'}), true);
await t('history create', setDoc(doc(bob,'teams','T1','history','h1'),{date:'2026-09-29',savedAtMs:1,savedBy:'bob',watches:[{name:'Varsity',members:['Maya L.'],workout:'CV',reps:1,splits:[],laps:[]}]}), true);
await t('history update fails', updateDoc(doc(bob,'teams','T1','history','h1'),{date:'2026-09-30'}), false);
await t('mal cannot write athletes', setDoc(doc(mal,'teams','T1','athletes','m'),ath('mal')), false);
console.log('team doc');
await t('bump pwVersion alone fails', updateDoc(doc(alice,'teams','T1'),{pwVersion:2}), false);
await t('rename team ok', updateDoc(doc(alice,'teams','T1'),{name:'Little Chute XC'}), true);
await t('delete team fails', deleteDoc(doc(alice,'teams','T1')), false);
console.log('change password (bob)');
await t('mal cannot bump with a key batch', (()=>{const b=writeBatch(mal); b.set(doc(mal,'teamKeys',K2),{teamId:'T1',pwVersion:2}); b.update(doc(mal,'teams','T1'),{pwVersion:2}); b.set(doc(mal,'teams','T1','members','mal'),{pwVersion:2,key:K2}); return b.commit();})(), false);
await t('bob changes password', (()=>{const b=writeBatch(bob); b.delete(doc(bob,'teamKeys',K1)); b.set(doc(bob,'teamKeys',K2),{teamId:'T1',pwVersion:2}); b.update(doc(bob,'teams','T1'),{pwVersion:2}); b.set(doc(bob,'teams','T1','members','bob'),{pwVersion:2,key:K2}); return b.commit();})(), true);
await t('bob still reads', getDocs(collection(bob,'teams','T1','athletes')), true);
await t('alice (old version) locked out of data', getDocs(collection(alice,'teams','T1','athletes')), false);
await t('alice locked out of team doc', getDoc(doc(alice,'teams','T1')), false);
await t('old key is gone', getDoc(doc(alice,'teamKeys',K1)).then(s=>{ if(s.exists()) throw new Error('still there'); }), true);
await t('alice cannot rejoin with the old key', setDoc(doc(alice,'teams','T1','members','alice'),{pwVersion:2,key:K1}), false);
await t('alice cannot rejoin claiming v1', setDoc(doc(alice,'teams','T1','members','alice'),{pwVersion:1,key:K1}), false);
await t('alice rejoins with the new key', setDoc(doc(alice,'teams','T1','members','alice'),{pwVersion:2,key:K2}), true);
const carol=env.authenticatedContext('carol').firestore();
await t('new phone (carol) joins after the change', setDoc(doc(carol,'teams','T1','members','carol'),{pwVersion:2,key:K2}), true);
await t('alice reads again', getDocs(collection(alice,'teams','T1','athletes')), true);
await t('history delete by member', deleteDoc(doc(alice,'teams','T1','history','h1')), true);
await t('alice leaves (deletes own membership)', deleteDoc(doc(alice,'teams','T1','members','alice')), true);
await t('after leaving, alice cannot read', getDocs(collection(alice,'teams','T1','athletes')), false);
console.log('second team isolation');
await t('mal creates team T2', createTeam(mal,'mal','T2',KO,'Other'), true);
await t('mal cannot read T1 with T2 membership', getDocs(collection(mal,'teams','T1','athletes')), false);
await t('mal cannot join T1 using T2 key', setDoc(doc(mal,'teams','T1','members','mal'),{pwVersion:1,key:KO}), false);
await t('bob cannot read T2', getDocs(collection(bob,'teams','T2','workouts')), false);
console.log(`\n${n-bad}/${n} passed`); await env.cleanup(); process.exit(bad?1:0);
