import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { doc, getDoc, getDocs, setDoc, updateDoc, deleteDoc, collection, writeBatch, serverTimestamp, arrayUnion } from 'firebase/firestore';
import fs from 'fs';
const env = await initializeTestEnvironment({ projectId: 'demo-ms', firestore: { rules: fs.readFileSync(new URL('../firestore.rules', import.meta.url),'utf8'), host:'127.0.0.1', port:8181 } });
const H=c=>c.repeat(64);
const K1=H('a'), K2=H('b'), KX=H('c'), KO=H('d'), K3=H('e');          // team password keys
const A1=H('1'), A2=H('2'), AX=H('3'), AO=H('4'), AL=H('5'), AN=H('6'); // admin keys
const db=u=>env.authenticatedContext(u).firestore();
const coach=db('coach'), mac=db('mac'), bob=db('bob'), mal=db('mal'), anon=env.unauthenticatedContext().firestore();
let n=0,bad=0; const t=async(name,p,ok)=>{ n++; try{ await (ok?assertSucceeds(p):assertFails(p)); console.log('  ok  ',name);}catch(e){ bad++; console.log('  FAIL',name,'--',String(e.message).split('\n')[0]);} };
const ath=(u,name='Maya L.',x={})=>({name,group:'Varsity',updatedAt:serverTimestamp(),updatedBy:u,...x});
function createTeam(d,u,tid,key,akey,name='Mustangs',o={}){ const b=writeBatch(d);
  b.set(doc(d,'teams',tid),{name,pwVersion:1,hasAdmin:true,adminVersion:1,createdAt:serverTimestamp(),...(o.team||{})});
  b.set(doc(d,'teamKeys',key),{teamId:tid,pwVersion:1});
  if(akey) b.set(doc(d,'adminKeys',akey),{teamId:tid,adminVersion:1});
  b.set(doc(d,'teams',tid,'members',u),{pwVersion:1,key,...(akey?{adminVersion:1,adminKey:akey}:{})});
  return b.commit(); }
function changePw(d,u,tid,oldK,newK,v,admin){ const b=writeBatch(d);
  b.delete(doc(d,'teamKeys',oldK)); b.set(doc(d,'teamKeys',newK),{teamId:tid,pwVersion:v+1});
  b.update(doc(d,'teams',tid),{pwVersion:v+1});
  b.set(doc(d,'teams',tid,'members',u),{pwVersion:v+1,key:newK,...(admin||{})}); return b.commit(); }
function setAdmin(d,u,tid,key,pwv,akey,av){ const b=writeBatch(d);
  b.set(doc(d,'adminKeys',akey),{teamId:tid,adminVersion:av});
  b.update(doc(d,'teams',tid),{hasAdmin:true,adminVersion:av});
  b.set(doc(d,'teams',tid,'members',u),{pwVersion:pwv,key,adminVersion:av,adminKey:akey}); return b.commit(); }

console.log('create');
await t('unauthenticated cannot create a team', createTeam(anon,'x','T0',KX,AX), false);
await t('create without an admin fails', createTeam(mal,'mal','T7',KX,null,'NoAdmin',{team:{}}), false);
await t('create with hasAdmin false fails', createTeam(mal,'mal','T7',KX,AX,'x',{team:{hasAdmin:false}}), false);
await t('coach creates team T1 with admin', createTeam(coach,'coach','T1',K1,A1), true);
await t('create with a taken password fails', createTeam(mal,'mal','T9',K1,AX), false);
await t('create reusing T1 admin key fails', createTeam(mal,'mal','T9',KX,A1), false);
console.log('privacy');
await t('mal cannot list teams', getDocs(collection(mal,'teams')), false);
await t('mal cannot list teamKeys', getDocs(collection(mal,'teamKeys')), false);
await t('mal cannot list adminKeys', getDocs(collection(mal,'adminKeys')), false);
await t('non-member cannot get an admin key even by hash', getDoc(doc(mal,'adminKeys',A1)), false);
await t('mal cannot get team T1', getDoc(doc(mal,'teams','T1')), false);
await t('mal cannot read coach membership', getDoc(doc(mal,'teams','T1','members','coach')), false);
console.log('join');
await t('mal cannot join with a wrong key', setDoc(doc(mal,'teams','T1','members','mal'),{pwVersion:1,key:KX}), false);
await t('mal cannot forge a team key', setDoc(doc(mal,'teamKeys',KX),{teamId:'T1',pwVersion:2}), false);
await t('bob joins with the right key', setDoc(doc(bob,'teams','T1','members','bob'),{pwVersion:1,key:K1}), true);
await t('bob reads team', getDoc(doc(bob,'teams','T1')), true);
console.log('non-admin limits (bob, admin exists)');
await t('bob cannot claim admin without a key', setDoc(doc(bob,'teams','T1','members','bob'),{pwVersion:1,key:K1,adminVersion:1}), false);
await t('bob cannot claim admin with a forged hash', setDoc(doc(bob,'teams','T1','members','bob'),{pwVersion:1,key:K1,adminVersion:1,adminKey:AX}), false);
await t('bob cannot create an admin key for T1', setDoc(doc(bob,'adminKeys',AX),{teamId:'T1',adminVersion:2}), false);
await t('bob cannot take over as "first admin"', setAdmin(bob,'bob','T1',K1,1,AX,2), false);
await t('bob cannot switch hasAdmin off', updateDoc(doc(bob,'teams','T1'),{hasAdmin:false}), false);
await t('bob cannot bump adminVersion', updateDoc(doc(bob,'teams','T1'),{adminVersion:2}), false);
await t('bob cannot rename the team', updateDoc(doc(bob,'teams','T1'),{name:'Bobs'}), false);
await t('bob cannot change the password', changePw(bob,'bob','T1',K1,KX,1), false);
await t('bob cannot delete the password key', deleteDoc(doc(bob,'teamKeys',K1)), false);
await t('bob cannot delete the admin key', deleteDoc(doc(bob,'adminKeys',A1)), false);
await t('bob can get the admin key only if he knows the hash (he does not: random id)', getDoc(doc(bob,'adminKeys',AX)), false);
console.log('open to every member');
await t('bob writes an athlete', setDoc(doc(bob,'teams','T1','athletes','a1'),ath('bob')), true);
await t('bob writes a workout', setDoc(doc(bob,'teams','T1','workouts','w1'),{name:'CV',reps:'5',rest:'1:30',restUnit:'mss',segments:[],updatedAt:serverTimestamp(),updatedBy:'bob'}), true);
await t('bob saves history', setDoc(doc(bob,'teams','T1','history','h1'),{date:'2026-09-30',savedAtMs:1,savedBy:'bob',watches:[]}), true);
await t('history cannot be deleted (2.6: soft delete only)', deleteDoc(doc(bob,'teams','T1','history','h1')), false);
await t('athlete name over 30 fails', setDoc(doc(bob,'teams','T1','athletes','a2'),ath('bob','x'.repeat(31))), false);
console.log('admin (coach)');
await t('coach renames the team', updateDoc(doc(coach,'teams','T1'),{name:'Little Chute XC'}), true);
await t('admin cannot switch hasAdmin off', updateDoc(doc(coach,'teams','T1'),{hasAdmin:false}), false);
await t('mac joins as member', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:1,key:K1}), true);
await t('mac gets the admin key by hash (member)', getDoc(doc(mac,'adminKeys',A1)), true);
await t('mac becomes admin with the passphrase', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:1,key:K1,adminVersion:1,adminKey:A1}), true);
await t('mac can rename', updateDoc(doc(mac,'teams','T1'),{name:'Little Chute XC'}), true);
console.log('password change keeps admin');
await t('coach changes the password, stays admin', changePw(coach,'coach','T1',K1,K2,1,{adminVersion:1,adminKey:A1}), true);
await t('bob locked out', getDocs(collection(bob,'teams','T1','athletes')), false);
await t('mac locked out too', getDoc(doc(mac,'teams','T1')), false);
await t('coach still admin: rename works', updateDoc(doc(coach,'teams','T1'),{name:'LCXC'}), true);
await t('mac cannot rejoin with the old key', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:2,key:K1,adminVersion:1,adminKey:A1}), false);
await t('mac rejoins with the new key and keeps admin', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:2,key:K2,adminVersion:1,adminKey:A1}), true);
await t('mac is admin again: rename works', updateDoc(doc(mac,'teams','T1'),{name:'Little Chute XC'}), true);
await t('bob rejoins as member', setDoc(doc(bob,'teams','T1','members','bob'),{pwVersion:2,key:K2}), true);
console.log('quiet rejoin keeps admin (new account)');
const coach2=db('coach-new-uid');
await t('new account rejoins with saved keys as admin', setDoc(doc(coach2,'teams','T1','members','coach-new-uid'),{pwVersion:2,key:K2,adminVersion:1,adminKey:A1}), true);
await t('new account is admin', updateDoc(doc(coach2,'teams','T1'),{name:'LCXC'}), true);
console.log('admin passphrase change');
await t('non-admin cannot change the admin passphrase', (()=>{ const b=writeBatch(bob); b.delete(doc(bob,'adminKeys',A1)); b.set(doc(bob,'adminKeys',A2),{teamId:'T1',adminVersion:2}); b.update(doc(bob,'teams','T1'),{adminVersion:2}); b.set(doc(bob,'teams','T1','members','bob'),{pwVersion:2,key:K2,adminVersion:2,adminKey:A2}); return b.commit(); })(), false);
await t('coach changes the admin passphrase', (()=>{ const b=writeBatch(coach); b.delete(doc(coach,'adminKeys',A1)); b.set(doc(coach,'adminKeys',A2),{teamId:'T1',adminVersion:2}); b.update(doc(coach,'teams','T1'),{adminVersion:2}); b.set(doc(coach,'teams','T1','members','coach'),{pwVersion:2,key:K2,adminVersion:2,adminKey:A2}); return b.commit(); })(), true);
await t('mac is no longer admin', updateDoc(doc(mac,'teams','T1'),{name:'Mac'}), false);
await t('mac is still a member', getDocs(collection(mac,'teams','T1','athletes')), true);
await t('mac cannot re-assert the old admin key', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:2,key:K2,adminVersion:1,adminKey:A1}), false);
await t('mac cannot claim the new version with the old key', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:2,key:K2,adminVersion:2,adminKey:A1}), false);
await t('mac becomes admin with the new passphrase', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:2,key:K2,adminVersion:2,adminKey:A2}), true);
await t('mac stops being admin on this device', setDoc(doc(mac,'teams','T1','members','mac'),{pwVersion:2,key:K2}), true);
await t('mac (not admin) cannot change the password', changePw(mac,'mac','T1',K2,K3,2), false);
console.log('legacy team (made by 2.0, no admin fields)');
await env.withSecurityRulesDisabled(async c=>{ const d=c.firestore();
  await setDoc(doc(d,'teams','L1'),{name:'Old',pwVersion:1,createdAt:new Date()}); await setDoc(doc(d,'teamKeys',KO),{teamId:'L1',pwVersion:1});
  await setDoc(doc(d,'teams','L1','members','bob'),{pwVersion:1,key:KO}); await setDoc(doc(d,'teams','L1','members','mal'),{pwVersion:1,key:KO}); });
await t('legacy: member reads', getDoc(doc(bob,'teams','L1')), true);
await t('legacy: nobody can change the password yet', changePw(bob,'bob','L1',KO,KX,1), false);
await t('legacy: nobody can rename yet', updateDoc(doc(bob,'teams','L1'),{name:'x'}), false);
await t('legacy: first-admin without a key fails', updateDoc(doc(bob,'teams','L1'),{hasAdmin:true,adminVersion:1}), false);
await t('legacy: first-admin cannot also rename', (()=>{ const b=writeBatch(bob); b.set(doc(bob,'adminKeys',AL),{teamId:'L1',adminVersion:1}); b.update(doc(bob,'teams','L1'),{hasAdmin:true,adminVersion:1,name:'Bobs'}); b.set(doc(bob,'teams','L1','members','bob'),{pwVersion:1,key:KO,adminVersion:1,adminKey:AL}); return b.commit(); })(), false);
await t('legacy: first-admin cannot skip versions', setAdmin(bob,'bob','L1',KO,1,AL,5), false);
await t('legacy: bob sets the first admin passphrase', setAdmin(bob,'bob','L1',KO,1,AL,1), true);
await t('legacy: mal (second) cannot set another', setAdmin(mal,'mal','L1',KO,1,AX,2), false);
await t('legacy: mal cannot set one at the same version', setAdmin(mal,'mal','L1',KO,1,AX,1), false);
await t('legacy: bob is admin, can change password', changePw(bob,'bob','L1',KO,KX,1,{adminVersion:1,adminKey:AL}), true);
console.log('console recovery: owner sets hasAdmin false');
await env.withSecurityRulesDisabled(async c=>{ await updateDoc(doc(c.firestore(),'teams','L1'),{hasAdmin:false}); });
await t('old admin loses admin', updateDoc(doc(bob,'teams','L1'),{name:'x'}), false);
await t('mal rejoins with the new password', setDoc(doc(mal,'teams','L1','members','mal'),{pwVersion:2,key:KX}), true);
await t('mal sets a new admin passphrase (version goes to 2)', setAdmin(mal,'mal','L1',KX,2,AN,2), true);
await t('old admin device still not admin (version 1 is stale)', updateDoc(doc(bob,'teams','L1'),{name:'x'}), false);
await t('old admin cannot re-assert old key', setDoc(doc(bob,'teams','L1','members','bob'),{pwVersion:2,key:KX,adminVersion:1,adminKey:AL}), false);
console.log('cross-team');
await t('T1 admin key cannot make an L1 admin', setDoc(doc(bob,'teams','L1','members','bob'),{pwVersion:2,key:KX,adminVersion:2,adminKey:A2}), false);
await t('L1 member cannot read T1', getDocs(collection(mal,'teams','T1','athletes')), false);
console.log('race mode');
const race=(u,o={})=>({name:'Invite',status:'running',gun:{local:1000,off:-5,by:'dev'},checkpoints:[{id:'c1',name:'Mile 1',dist:1609.34}],runners:[{id:'a1',name:'Maya L.',group:'V',goal:1170}],updatedAt:serverTimestamp(),updatedBy:u,...o});
const mark=(u,o={})=>({cp:'c1',local:5000,off:-5,runnerId:'a1',by:'dev',updatedAt:serverTimestamp(),updatedBy:u,...o});
await t('member (bob) creates a race', setDoc(doc(bob,'teams','T1','races','r1'),race('bob')), true);
await t('member reads races', getDocs(collection(bob,'teams','T1','races')), true);
await t('outsider cannot read races', getDocs(collection(mal,'teams','T1','races')), false);
await t('outsider cannot create a race', setDoc(doc(mal,'teams','T1','races','r2'),race('mal')), false);
await t('race with a bad status fails', setDoc(doc(bob,'teams','T1','races','r3'),race('bob',{status:'paused'})), false);
await t('race with extra fields fails', setDoc(doc(bob,'teams','T1','races','r3'),race('bob',{secret:1})), false);
await t('race updatedBy spoof fails', setDoc(doc(bob,'teams','T1','races','r3'),race('coach')), false);
await t('races cannot be deleted', deleteDoc(doc(bob,'teams','T1','races','r1')), false);
await t('member records a mark', setDoc(doc(bob,'teams','T1','races','r1','marks','m1'),mark('bob')), true);
await t('unassigned mark (runnerId null) ok', setDoc(doc(bob,'teams','T1','races','r1','marks','m2'),mark('bob',{runnerId:null,off:null})), true);
await t('another member assigns it', updateDoc(doc(coach,'teams','T1','races','r1','marks','m2'),{runnerId:'a1',updatedAt:serverTimestamp(),updatedBy:'coach'}), true);
await t('mark with a string time fails', setDoc(doc(bob,'teams','T1','races','r1','marks','m3'),mark('bob',{local:'5000'})), false);
await t('mark with extra fields fails', setDoc(doc(bob,'teams','T1','races','r1','marks','m3'),mark('bob',{note:'x'})), false);
await t('outsider cannot add a mark', setDoc(doc(mal,'teams','T1','races','r1','marks','m9'),mark('mal')), false);
await t('outsider cannot read marks', getDocs(collection(mal,'teams','T1','races','r1','marks')), false);
await t('a mark cannot be deleted (2.6: removing is a new version)', deleteDoc(doc(bob,'teams','T1','races','r1','marks','m1')), false);
await t('member ends the race', updateDoc(doc(coach,'teams','T1','races','r1'),{status:'done',updatedAt:serverTimestamp(),updatedBy:'coach'}), true);
await t('race history entry ok', setDoc(doc(bob,'teams','T1','history','hr'),{date:'2026-10-01',savedAtMs:2,savedBy:'bob',watches:[],kind:'race',race:{name:'Invite',checkpoints:[],rows:[]}}), true);
await t('history with another kind fails', setDoc(doc(bob,'teams','T1','history','hx'),{date:'2026-10-01',savedAtMs:2,savedBy:'bob',watches:[],kind:'other'}), false);
await t('history race without kind fails', setDoc(doc(bob,'teams','T1','history','hy'),{date:'2026-10-01',savedAtMs:2,savedBy:'bob',watches:[],race:{}}), false);
console.log('clock');
await t('device writes its own server timestamp', setDoc(doc(bob,'clock','bob'),{at:serverTimestamp()}), true);
await t('device reads its own clock doc', getDoc(doc(bob,'clock','bob')), true);
await t('client-chosen time is rejected', setDoc(doc(bob,'clock','bob'),{at:new Date(Date.now()-60000)}), false);
await t('cannot write another device clock', setDoc(doc(bob,'clock','coach'),{at:serverTimestamp()}), false);
await t('cannot read another device clock', getDoc(doc(bob,'clock','coach')), false);
await t('unauthenticated cannot write a clock', setDoc(doc(anon,'clock','x'),{at:serverTimestamp()}), false);
await t('cannot list clocks', getDocs(collection(bob,'clock')), false);

console.log('race mode 2.4: coach names, presence, discard');
await t('mark with a coach name ok', setDoc(doc(bob,'teams','T1','races','r1','marks','n1'),mark('bob',{byName:'Coach Bob'})), true);
await t('mark with byName null ok (pre-2.4 shape)', setDoc(doc(bob,'teams','T1','races','r1','marks','n2'),mark('bob',{byName:null})), true);
await t('mark with a 31-char name fails', setDoc(doc(bob,'teams','T1','races','r1','marks','n3'),mark('bob',{byName:'x'.repeat(31)})), false);
await t('mark with a numeric name fails', setDoc(doc(bob,'teams','T1','races','r1','marks','n3'),mark('bob',{byName:5})), false);
await t('mark without byName still ok (2.3 phones)', setDoc(doc(bob,'teams','T1','races','r1','marks','n4'),mark('bob')), true);
const pres=(o={})=>({cp:'c1',name:'Coach Bob',ver:'2.4.0',at:serverTimestamp(),...o});
await t('coach writes own presence', setDoc(doc(bob,'teams','T1','races','r1','coaches','bob'),pres()), true);
await t('coach updates own presence (new checkpoint)', setDoc(doc(bob,'teams','T1','races','r1','coaches','bob'),pres({cp:'c2'})), true);
await t('member reads presence', getDocs(collection(coach,'teams','T1','races','r1','coaches')), true);
await t('cannot write another coach presence', setDoc(doc(bob,'teams','T1','races','r1','coaches','coach'),pres()), false);
await t('presence with client time fails', setDoc(doc(bob,'teams','T1','races','r1','coaches','bob'),pres({at:new Date()})), false);
await t('presence with extra fields fails', setDoc(doc(bob,'teams','T1','races','r1','coaches','bob'),pres({uid:'x'})), false);
await t('presence without a version fails', setDoc(doc(bob,'teams','T1','races','r1','coaches','bob'),pres({ver:''})), false);
await t('outsider cannot read presence', getDocs(collection(mal,'teams','T1','races','r1','coaches')), false);
await t('outsider cannot write presence', setDoc(doc(mal,'teams','T1','races','r1','coaches','mal'),pres()), false);
const disc=(u,o={})=>({status:'discarded',discardedFrom:'running',deletedAt:serverTimestamp(),deletedBy:u,updatedAt:serverTimestamp(),updatedBy:u,...o});
const back=(u,o={})=>({status:'running',restoredAt:serverTimestamp(),restoredBy:u,updatedAt:serverTimestamp(),updatedBy:u,...o});
const exists=(p)=>p.then(s=>{ if(!s.exists()) throw new Error('document is gone'); });
await setDoc(doc(bob,'teams','T1','races','rd'),race('bob'));
await setDoc(doc(bob,'teams','T1','races','rd','marks','d1'),mark('bob'));
await setDoc(doc(bob,'teams','T1','races','rd','coaches','bob'),pres());
console.log('2.6: discard keeps everything; only a restore brings it back');
await t('a discard that also empties the race fails', updateDoc(doc(bob,'teams','T1','races','rd'),disc('bob',{name:'',runners:[]})), false);
await t('a discard with a forged deletedBy fails', updateDoc(doc(bob,'teams','T1','races','rd'),disc('bob',{deletedBy:'coach'})), false);
await t('outsider cannot discard', updateDoc(doc(mal,'teams','T1','races','rd'),disc('mal')), false);
await t('member discards: only the status changes', updateDoc(doc(coach,'teams','T1','races','rd'),disc('coach')), true);
await t('its marks are still there', exists(getDoc(doc(bob,'teams','T1','races','rd','marks','d1'))), true);
await t('marks of a discarded race cannot be deleted', deleteDoc(doc(bob,'teams','T1','races','rd','marks','d1')), false);
await t('discarded race cannot be revived by re-sending it (offline phone)', setDoc(doc(bob,'teams','T1','races','rd'),race('bob')), false);
await t('discarded race cannot be ended either', updateDoc(doc(bob,'teams','T1','races','rd'),{status:'done',updatedAt:serverTimestamp(),updatedBy:'bob'}), false);
await t('no presence on a discarded race', setDoc(doc(bob,'teams','T1','races','rd','coaches','bob'),pres()), false);
await t('an offline phone\'s tap on a discarded race is kept (for a restore)', setDoc(doc(bob,'teams','T1','races','rd','marks','d2'),mark('bob')), true);
await t('a restore in another coach\'s name fails', updateDoc(doc(bob,'teams','T1','races','rd'),back('bob',{restoredBy:'coach'})), false);
await t('a restore that also changes the race fails', updateDoc(doc(bob,'teams','T1','races','rd'),back('bob',{name:'Other'})), false);
await t('outsider cannot restore', updateDoc(doc(mal,'teams','T1','races','rd'),back('mal')), false);
await t('member restores the race', updateDoc(doc(bob,'teams','T1','races','rd'),back('bob')), true);
await t('restored race has all its marks', exists(getDoc(doc(coach,'teams','T1','races','rd','marks','d2'))).then(()=>exists(getDoc(doc(coach,'teams','T1','races','rd','marks','d1')))), true);
await t('races still cannot be deleted', deleteDoc(doc(bob,'teams','T1','races','rd')), false);
await t('a race discarded before it was ever sent can be created discarded', setDoc(doc(bob,'teams','T1','races','rnew'),{...race('bob'),status:'discarded',discardedFrom:'setup',deletedAt:serverTimestamp(),deletedBy:'bob'}), true);
await t('marks on a race not created yet are ok (offline order)', setDoc(doc(bob,'teams','T1','races','rlater','marks','x1'),mark('bob')), true);
await t('a done race still accepts time edits', setDoc(doc(bob,'teams','T1','races','r1','marks','n1'),mark('bob',{local:6000,byName:'Coach Bob'})), true);

console.log('2.5: courses, PRs, race course + goal source');
const course=(u,o={})=>({name:'Heritage Park',checkpoints:[{id:'c1',name:'Mile 1',dist:1609.34,unit:'mi'}],updatedAt:serverTimestamp(),updatedBy:u,...o});
await t('member saves a course', setDoc(doc(bob,'teams','T1','courses','k1'),course('bob')), true);
await t('another member updates it', setDoc(doc(coach,'teams','T1','courses','k1'),course('coach',{name:'Heritage Park 5K'})), true);
await t('member reads courses', getDocs(collection(bob,'teams','T1','courses')), true);
await t('outsider cannot read courses', getDocs(collection(mal,'teams','T1','courses')), false);
await t('outsider cannot save a course', setDoc(doc(mal,'teams','T1','courses','k2'),course('mal')), false);
await t('course without a name fails', setDoc(doc(bob,'teams','T1','courses','k2'),course('bob',{name:''})), false);
await t('course name over 40 fails', setDoc(doc(bob,'teams','T1','courses','k2'),course('bob',{name:'x'.repeat(41)})), false);
await t('course with 13 checkpoints fails', setDoc(doc(bob,'teams','T1','courses','k2'),course('bob',{checkpoints:Array(13).fill({name:'x'})})), false);
await t('course with extra fields fails', setDoc(doc(bob,'teams','T1','courses','k2'),course('bob',{secret:1})), false);
await t('course updatedBy spoof fails', setDoc(doc(bob,'teams','T1','courses','k2'),course('coach')), false);
await t('a course cannot be deleted (2.6)', deleteDoc(doc(bob,'teams','T1','courses','k1')), false);
const prs=(u,o={})=>({list:[{dist:5000,t:1122.4}],updatedAt:serverTimestamp(),updatedBy:u,...o});
await t('member saves PRs', setDoc(doc(bob,'teams','T1','prs','a1'),prs('bob')), true);
await t('member reads PRs', getDocs(collection(coach,'teams','T1','prs')), true);
await t('outsider cannot read PRs', getDocs(collection(mal,'teams','T1','prs')), false);
await t('outsider cannot write PRs', setDoc(doc(mal,'teams','T1','prs','a1'),prs('mal')), false);
await t('PRs with 61 entries fail (deleted ones stay in the list)', setDoc(doc(bob,'teams','T1','prs','a1'),prs('bob',{list:Array(61).fill({dist:5000,t:1})})), false);
await t('empty PR list fails (delete instead)', setDoc(doc(bob,'teams','T1','prs','a1'),prs('bob',{list:[]})), false);
await t('PRs with extra fields fail', setDoc(doc(bob,'teams','T1','prs','a1'),prs('bob',{name:'x'})), false);
await t('PRs updatedBy spoof fails', setDoc(doc(bob,'teams','T1','prs','a1'),prs('coach')), false);
await t('PRs cannot be deleted (2.6)', deleteDoc(doc(bob,'teams','T1','prs','a1')), false);
await t('race with a course and goal source ok', setDoc(doc(bob,'teams','T1','races','r5'),race('bob',{courseId:'k1',goalSrc:'pr'})), true);
await t('race with courseId null ok', setDoc(doc(bob,'teams','T1','races','r5'),race('bob',{courseId:null,goalSrc:'custom'})), true);
await t('race with a numeric courseId fails', setDoc(doc(bob,'teams','T1','races','r5'),race('bob',{courseId:7})), false);
await t('race with a long goal source fails', setDoc(doc(bob,'teams','T1','races','r5'),race('bob',{goalSrc:'x'.repeat(11)})), false);
await t('2.4 race shape (no course fields) still ok', setDoc(doc(bob,'teams','T1','races','r5'),race('bob')), true);

console.log('2.6 data safety: no hard deletes, soft delete + restore, append-only corrections, purge, devices');
const ad=db('ad26'), mb=db('mb26'), ex=db('ex26');
await t('admin creates team T26', createTeam(ad,'ad26','T26',H('f'),H('7')), true);
await t('member joins T26', setDoc(doc(mb,'teams','T26','members','mb26'),{pwVersion:1,key:H('f')}), true);
const T=(...p)=>['teams','T26',...p], D=(d,...p)=>doc(d,...T(...p));
const SD=(u,o={})=>({deleted:true,deletedAt:serverTimestamp(),deletedBy:u,updatedAt:serverTimestamp(),updatedBy:u,...o});
const UNSD=(u,o={})=>({deleted:false,restoredAt:serverTimestamp(),restoredBy:u,updatedAt:serverTimestamp(),updatedBy:u,...o});
const W=(u,o={})=>({name:'CV 5x1000',reps:5,rest:'1:30',restUnit:'mss',segments:[{dist:1000}],updatedAt:serverTimestamp(),updatedBy:u,...o});
const CO=(u,o={})=>({name:'Kiel HS',checkpoints:[{id:'c1',name:'Mile 1',dist:1609.34,unit:'mi'}],updatedAt:serverTimestamp(),updatedBy:u,...o});
const has=(p,f,v)=>p.then(s=>{ if(!s.exists()) throw new Error('gone'); if(f && JSON.stringify(s.data()[f])!==JSON.stringify(v)) throw new Error(f+' is '+JSON.stringify(s.data()[f])); });
await setDoc(D(mb,'athletes','a1'),ath('mb26','Maya L.')); await setDoc(D(mb,'athletes','a2'),ath('mb26','Jonah K.'));
await setDoc(D(mb,'workouts','w1'),W('mb26')); await setDoc(D(mb,'courses','k1'),CO('mb26'));
await setDoc(D(mb,'prs','a1'),{list:[{dist:5000,t:1141}],updatedAt:serverTimestamp(),updatedBy:'mb26'});
// hard deletes are refused, for members and (outside a purge) for the admin
for(const [label,path] of [['runner',['athletes','a1']],['workout',['workouts','w1']],['course',['courses','k1']],['PR list',['prs','a1']]]){
  await t(`member cannot hard-delete a ${label}`, deleteDoc(D(mb,...path)), false);
  await t(`admin cannot hard-delete a ${label} without a purge`, deleteDoc(D(ad,...path)), false);
}
// soft delete keeps the content; it can't be used to blank it
await t('soft delete of a runner (flags only)', updateDoc(D(mb,'athletes','a1'),SD('mb26')), true);
await t('soft-deleted runner still has its name', has(getDoc(D(ad,'athletes','a1')),'name','Maya L.'), true);
await t('a soft delete that renames fails', updateDoc(D(mb,'athletes','a2'),SD('mb26',{name:'x'})), false);
await t('a soft delete in another coach\'s name fails', updateDoc(D(mb,'athletes','a2'),SD('ad26')), false);
await t('a soft delete with a made-up time fails', updateDoc(D(mb,'athletes','a2'),SD('mb26',{deletedAt:new Date(0)})), false);
await t('a normal write cannot set deleted', setDoc(D(mb,'athletes','a2'),ath('mb26','Jonah K.',{deleted:true})), false);
await t('outsider cannot soft delete', updateDoc(D(ex,'athletes','a2'),SD('ex26')), false);
await t('restore by clearing the flag', updateDoc(D(ad,'athletes','a1'),UNSD('ad26')), true);
await t('restored runner is back with its name', has(getDoc(D(mb,'athletes','a1')),'deleted',false), true);
await t('restore in another coach\'s name fails', updateDoc(D(mb,'athletes','a1'),SD('mb26')).then(()=>updateDoc(D(mb,'athletes','a1'),UNSD('mb26',{restoredBy:'someone-else'}))), false);
await t('restore by writing the runner again also works', setDoc(D(mb,'athletes','a1'),ath('mb26','Maya L.')), true);
await t('workout soft delete + restore', updateDoc(D(mb,'workouts','w1'),SD('mb26')).then(()=>updateDoc(D(mb,'workouts','w1'),UNSD('mb26'))).then(()=>has(getDoc(D(mb,'workouts','w1')),'name','CV 5x1000')), true);
await t('course soft delete + restore', updateDoc(D(mb,'courses','k1'),SD('mb26')).then(()=>setDoc(D(mb,'courses','k1'),CO('mb26'))).then(()=>has(getDoc(D(mb,'courses','k1')),'name','Kiel HS')), true);
await t('a soft-deleted workout that blanks its segments fails', updateDoc(D(mb,'workouts','w1'),SD('mb26',{segments:[]})), false);
await t('a removed PR stays in the list marked deleted', setDoc(D(mb,'prs','a1'),{list:[{dist:5000,t:1141,deleted:true,deletedAt:1,deletedBy:'mb26'}],updatedAt:serverTimestamp(),updatedBy:'mb26'}), true);
// history: soft delete, restore, append-only corrections
await setDoc(D(mb,'history','h1'),{date:'2026-10-02',savedAtMs:1,savedBy:'mb26',watches:[],kind:'race',race:{name:'Kiel',checkpoints:[],rows:[],marks:[]},edits:[]});
const ed=(u,o={})=>({mid:'m1',ci:0,rid:'a1',t:372.4,deleted:false,chosen:false,uid:u,dev:'d',byName:'Coach',at:1,...o});
await t('history cannot be deleted', deleteDoc(D(mb,'history','h1')), false);
await t('history soft delete', updateDoc(D(mb,'history','h1'),{deleted:true,deletedAt:serverTimestamp(),deletedBy:'mb26'}), true);
await t('history soft delete cannot touch the results', updateDoc(D(mb,'history','h2x'),{deleted:true}).catch(e=>{ throw e; }), false);
await t('history restore', updateDoc(D(ad,'history','h1'),{deleted:false,restoredAt:serverTimestamp(),restoredBy:'ad26'}), true);
await t('a correction is appended', updateDoc(D(mb,'history','h1'),{edits:arrayUnion(ed('mb26'))}), true);
await t('a second correction by another coach is appended', updateDoc(D(ad,'history','h1'),{edits:arrayUnion(ed('ad26',{t:370,at:2}))}), true);
await t('both corrections are kept, in order', has(getDoc(D(mb,'history','h1')),'edits',[ed('mb26'),ed('ad26',{t:370,at:2})]), true);
await t('rewriting an earlier correction fails', updateDoc(D(mb,'history','h1'),{edits:[ed('mb26',{t:1}),ed('ad26',{t:370,at:2}),ed('mb26',{at:3})]}), false);
await t('removing a correction fails', updateDoc(D(mb,'history','h1'),{edits:[ed('mb26')]}), false);
await t('a correction in another coach\'s name fails', updateDoc(D(mb,'history','h1'),{edits:arrayUnion(ed('ad26',{at:9}))}), false);
await t('a correction cannot change the saved results too', updateDoc(D(mb,'history','h1'),{edits:arrayUnion(ed('mb26',{at:4})),race:{name:'x',rows:[]}}), false);
await t('outsider cannot add a correction', updateDoc(D(ex,'history','h1'),{edits:arrayUnion(ed('ex26',{at:5}))}), false);
// marks: versions only grow
await setDoc(D(mb,'races','r1'),{name:'Kiel',status:'running',gun:{local:0,off:0,by:'d'},checkpoints:[{id:'c1',name:'Mile 1',dist:1609}],runners:[{id:'a1',name:'Maya L.'},{id:'a2',name:'Jonah K.'}],updatedAt:serverTimestamp(),updatedBy:'mb26'});
const tap=(u,o={})=>({cp:'c1',local:360000,off:0,runnerId:'a1',by:'d',byName:'Coach',updatedAt:serverTimestamp(),updatedBy:u,...o});
const v=(u,o={})=>({cp:'c1',runnerId:'a1',local:360000,off:0,deleted:false,chosen:false,uid:u,dev:'d',byName:'Coach',at:1,...o});
await t('a fresh tap (2.4 shape, no versions) is accepted', setDoc(D(mb,'races','r1','marks','m1'),tap('mb26')), true);
await t('a fresh tap marked deleted without versions fails', setDoc(D(mb,'races','r1','marks','m9'),tap('mb26',{deleted:true})), false);
await t('first correction: original + new version', updateDoc(D(mb,'races','r1','marks','m1'),{local:361000,deleted:false,chosen:false,hist:[v(''),v('mb26',{local:361000,at:2})],updatedAt:serverTimestamp(),updatedBy:'mb26'}), true);
await t('second correction by another coach (arrayUnion)', updateDoc(D(ad,'races','r1','marks','m1'),{runnerId:'a2',hist:arrayUnion(v('ad26',{local:361000,runnerId:'a2',at:3})),updatedAt:serverTimestamp(),updatedBy:'ad26'}), true);
await t('the mark keeps all three versions', getDoc(D(mb,'races','r1','marks','m1')).then(s=>{ if(s.data().hist.length!==3) throw new Error('hist '+s.data().hist.length); }), true);
await t('a correction whose fields don\'t match its newest version fails', updateDoc(D(mb,'races','r1','marks','m1'),{local:1,hist:arrayUnion(v('mb26',{local:2,runnerId:'a2',at:4})),updatedAt:serverTimestamp(),updatedBy:'mb26'}), false);
await t('rewriting an old version fails', updateDoc(D(mb,'races','r1','marks','m1'),{hist:[v('',{local:1}),v('mb26',{local:361000,at:2}),v('ad26',{local:361000,runnerId:'a2',at:3})],updatedAt:serverTimestamp(),updatedBy:'mb26'}), false);
await t('dropping versions fails', updateDoc(D(mb,'races','r1','marks','m1'),{hist:[v('ad26',{local:361000,runnerId:'a2',at:3})],updatedAt:serverTimestamp(),updatedBy:'mb26'}), false);
await t('a version in another coach\'s name fails', updateDoc(D(mb,'races','r1','marks','m1'),{local:362000,hist:arrayUnion(v('ad26',{local:362000,runnerId:'a2',at:5})),updatedAt:serverTimestamp(),updatedBy:'mb26'}), false);
await t('removing a time = a new version with deleted:true', updateDoc(D(mb,'races','r1','marks','m1'),{deleted:true,hist:arrayUnion(v('mb26',{local:361000,runnerId:'a2',deleted:true,at:6})),updatedAt:serverTimestamp(),updatedBy:'mb26'}), true);
await t('restoring it = another version', updateDoc(D(ad,'races','r1','marks','m1'),{deleted:false,hist:arrayUnion(v('ad26',{local:361000,runnerId:'a2',at:7})),updatedAt:serverTimestamp(),updatedBy:'ad26'}), true);
await t('a versioned mark can\'t be quietly edited without a version', updateDoc(D(mb,'races','r1','marks','m1'),{local:1,updatedAt:serverTimestamp(),updatedBy:'mb26'}), false);
await t('marks cannot be deleted by members', deleteDoc(D(mb,'races','r1','marks','m1')), false);
await t('admin cannot delete a mark without a purge', deleteDoc(D(ad,'races','r1','marks','m1')), false);
// purge (admin only)
await setDoc(D(mb,'races','r1','marks','m2'),tap('mb26',{runnerId:'a1'}));
const purge=(d,u,id,extra=(b)=>{})=>{ const b=writeBatch(d); b.set(D(d,'purges',id),{at:serverTimestamp(),by:u}); extra(b); return b.commit(); };
await t('member cannot purge a runner', purge(mb,'mb26','a1',b=>b.delete(D(mb,'athletes','a1'))), false);
await t('admin purge record with a name in it fails', (()=>{ const b=writeBatch(ad); b.set(D(ad,'purges','a1'),{at:serverTimestamp(),by:'ad26',name:'Maya'}); return b.commit(); })(), false);
await t('admin purges a runner: record + athlete + PRs + their marks + history rewrite', purge(ad,'ad26','a1',b=>{ b.delete(D(ad,'athletes','a1')); b.delete(D(ad,'prs','a1')); b.delete(D(ad,'races','r1','marks','m2'));
  b.update(D(ad,'history','h1'),{race:{name:'Kiel',checkpoints:[],rows:[],marks:[]},edits:[],purgedFor:'a1'}); }), true);
await t('the purge record cannot be changed or removed', updateDoc(D(ad,'purges','a1'),{by:'x'}).catch(e=>{ throw e; }), false);
await t('…or removed', deleteDoc(D(ad,'purges','a1')), false);
await t('members can read purge records (to scrub their phones)', getDocs(collection(mb,...T('purges'))), true);
await t('outsider cannot read purge records', getDocs(collection(ex,...T('purges'))), false);
await t('a purge does not unlock deleting another runner', deleteDoc(D(ad,'athletes','a2')), false);
// devices
await t('a phone writes its own version record', setDoc(D(mb,'devices','mb26'),{ver:'2.6.0',name:'Coach Ben',seen:serverTimestamp()}), true);
await t('members read every phone\'s version', getDocs(collection(ad,...T('devices'))), true);
await t('cannot write another phone\'s record', setDoc(D(mb,'devices','ad26'),{ver:'2.6.0',name:'x',seen:serverTimestamp()}), false);
await t('device record with a made-up time fails', setDoc(D(mb,'devices','mb26'),{ver:'2.6.0',name:'x',seen:new Date(0)}), false);
await t('outsider cannot read devices', getDocs(collection(ex,...T('devices'))), false);

console.log('2.7: series, meets, Girls/Boys, race meet and division, meet links');
const SE=(u,o={})=>({name:'Kiel Invite',updatedAt:serverTimestamp(),updatedBy:u,...o});
const ME=(u,o={})=>({seriesId:'s1',courseId:'k1',date:'2026-09-03',time:'4:00 PM',kind:'Invite',levels:['JV','V'],season:2026,updatedAt:serverTimestamp(),updatedBy:u,...o});
await t('member creates a series', setDoc(D(mb,'series','s1'),SE('mb26')), true);
await t('series name over 40 fails', setDoc(D(mb,'series','s2'),SE('mb26',{name:'x'.repeat(41)})), false);
await t('series with extra fields fails', setDoc(D(mb,'series','s2'),SE('mb26',{year:2026})), false);
await t('outsider cannot read series', getDocs(collection(ex,...T('series'))), false);
await t('member renames a series (every year follows)', setDoc(D(ad,'series','s1'),SE('ad26',{name:'Kiel Cross Country Invite'})), true);
await t('series cannot be deleted', deleteDoc(D(mb,'series','s1')), false);
await t('series soft delete + restore', updateDoc(D(mb,'series','s1'),SD('mb26')).then(()=>updateDoc(D(mb,'series','s1'),UNSD('mb26'))), true);
await t('member adds a meet', setDoc(D(mb,'meets','m1'),ME('mb26')), true);
await t('meet with an undated (new season) date ok', setDoc(D(mb,'meets','m2'),ME('mb26',{date:'',season:2027})), true);
await t('meet with a bad date fails', setDoc(D(mb,'meets','m3'),ME('mb26',{date:'9/3/2026'})), false);
await t('meet with an unknown level fails', setDoc(D(mb,'meets','m3'),ME('mb26',{levels:['V','Frosh']})), false);
await t('meet without levels fails', setDoc(D(mb,'meets','m3'),ME('mb26',{levels:[]})), false);
await t('meet without a series fails', setDoc(D(mb,'meets','m3'),ME('mb26',{seriesId:''})), false);
await t('meet with a text season fails', setDoc(D(mb,'meets','m3'),ME('mb26',{season:'2026'})), false);
await t('meet updatedBy spoof fails', setDoc(D(mb,'meets','m3'),ME('ad26')), false);
await t('outsider cannot add a meet', setDoc(D(ex,'meets','m3'),ME('ex26')), false);
await t('meets cannot be deleted', deleteDoc(D(mb,'meets','m1')), false);
await t('meet soft delete keeps it (flags only)', updateDoc(D(mb,'meets','m1'),SD('mb26')).then(()=>has(getDoc(D(ad,'meets','m1')),'date','2026-09-03')), true);
await t('meet restore', updateDoc(D(ad,'meets','m1'),UNSD('ad26')), true);
await t('runner marked Girls', setDoc(D(mb,'athletes','a2'),ath('mb26','Jonah K.',{gender:'G'})), true);
await t('runner marked Boys', setDoc(D(mb,'athletes','a2'),ath('mb26','Jonah K.',{gender:'B'})), true);
await t('runner with blank gender is left out (ok)', setDoc(D(mb,'athletes','a2'),ath('mb26','Jonah K.')), true);
await t('runner with another gender value fails', setDoc(D(mb,'athletes','a2'),ath('mb26','Jonah K.',{gender:'X'})), false);
const race27=(u,o={})=>({name:'Kiel Invite, Girls Varsity',status:'setup',gun:null,checkpoints:[],runners:[],courseId:'k1',goalSrc:'sb',meetId:'m1',division:'GV',updatedAt:serverTimestamp(),updatedBy:u,...o});
await t('race with a meet and division ok', setDoc(D(mb,'races','r27'),race27('mb26')), true);
await t('race with an unknown division fails', setDoc(D(mb,'races','r28'),race27('mb26',{division:'Frosh'})), false);
await t('race with no meet (null) ok', setDoc(D(mb,'races','r28'),race27('mb26',{meetId:null,division:''})), true);
await setDoc(D(mb,'history','h27'),{date:'2025-09-04',savedAtMs:1,savedBy:'mb26',watches:[],kind:'race',race:{name:'Kiel 2025',checkpoints:[],rows:[],marks:[]},edits:[]});
const link=(u,o={})=>({op:'link',meetId:'m1',seriesId:'s1',division:'GV',courseId:'k1',uid:u,dev:'d',byName:'Coach',at:5,...o});
await t('linking a past race to a meet is an appended edit', updateDoc(D(mb,'history','h27'),{edits:arrayUnion(link('mb26'))}), true);
await t('unlinking is another appended edit', updateDoc(D(ad,'history','h27'),{edits:arrayUnion(link('ad26',{meetId:null,seriesId:null,division:'',at:6}))}), true);
await t('a link in another coach\'s name fails', updateDoc(D(mb,'history','h27'),{edits:arrayUnion(link('ad26',{at:7}))}), false);
await t('a link cannot rewrite the saved results', updateDoc(D(mb,'history','h27'),{edits:arrayUnion(link('mb26',{at:8})),race:{name:'x'}}), false);
// ---- 2.9.0: minimum app version on the team (admin only, additive) ----
const TD=u=>doc(u,'teams','T26');
await t('admin sets the minimum app version', updateDoc(TD(ad),{minVersion:'2.9.0'}), true);
await t('admin turns it off (empty)', updateDoc(TD(ad),{minVersion:''}), true);
await t('member cannot set the minimum version', updateDoc(TD(mb),{minVersion:'2.9.0'}), false);
await t('outsider cannot set the minimum version', updateDoc(TD(ex),{minVersion:'2.9.0'}), false);
await t('minimum version must look like a version', updateDoc(TD(ad),{minVersion:'latest'}), false);
await t('minimum version must be text', updateDoc(TD(ad),{minVersion:290}), false);
await t('minimum version cannot ride along with a password bump', updateDoc(TD(ad),{minVersion:'2.9.0',pwVersion:99}), false);
await t('minimum version cannot hide a rename by a member', updateDoc(TD(mb),{minVersion:'2.9.0',name:'Hijack'}), false);
await t('admin rename still works (2.1 rules unchanged)', updateDoc(TD(ad),{name:'Team 26'}), true);
await t('member still cannot rename', updateDoc(TD(mb),{name:'Nope'}), false);
await t('a member still reads the team with minVersion set', updateDoc(TD(ad),{minVersion:'2.9.0'}).then(()=>getDoc(TD(mb))), true);
// ---- 2.9.0: official results (imported career history): admin writes, members read, soft delete only ----
const OD=(u,id)=>doc(u,'teams','T26','official',id);
const OF=(u,o={})=>({importId:'imp1',part:0,parts:1,importedAt:1,by:u,byName:'Coach',format:'mustang-splits-history/v1',source:'test',generated:'',
  results:[{k:'h|2025-09-04|5000|1200.0',aid:'a1',name:'Maya L.',g:'G',season:2025,grade:11,level:'HS',dist:5000,date:'2025-09-04',t:1200,place:12,meet:'Kiel Invite',seriesId:'s1',meetId:'m1',courseId:'k1',division:'GV'}],
  matches:{h:'a1'},updatedAt:serverTimestamp(),updatedBy:u,...o});
await t('admin saves an import', setDoc(OD(ad,'imp1'),OF('ad26')), true);
await t('member reads official results', getDoc(OD(mb,'imp1')), true);
await t('outsider cannot read official results', getDoc(OD(ex,'imp1')), false);
await t('member cannot import (admin only)', setDoc(OD(mb,'imp2'),OF('mb26')), false);
await t('import in another coach\'s name fails', setDoc(OD(ad,'imp2'),OF('mb26')), false);
await t('import with an extra field fails', setDoc(OD(ad,'imp2'),OF('ad26',{fullNames:['x']})), false);
await t('import with no results fails', setDoc(OD(ad,'imp2'),OF('ad26',{results:[]})), false);
await t('import with too many results fails', setDoc(OD(ad,'imp2'),OF('ad26',{results:Array.from({length:801},(_,i)=>({k:String(i)}))})), false);
await t('an import cannot be rewritten', setDoc(OD(ad,'imp1'),OF('ad26',{source:'changed'})), false);
await t('official results cannot be deleted', deleteDoc(OD(ad,'imp1')), false);
await t('member cannot undo an import', updateDoc(OD(mb,'imp1'),SD('mb26')), false);
await t('admin undoes an import (soft delete keeps it)', updateDoc(OD(ad,'imp1'),SD('ad26')).then(()=>has(getDoc(OD(mb,'imp1')),'source','test')), true);
await t('admin restores the import', updateDoc(OD(ad,'imp1'),UNSD('ad26')), true);
// 2.9.1: Varsity/JV levels are appended to edits (admin only)
const LV=(u,o={})=>({op:'level',k:'h|2025-09-04|5000|1200.0',level:'V',uid:u,dev:'d',byName:'Coach',at:1,...o});
await t('admin sets a Varsity/JV level (appended edit)', updateDoc(OD(ad,'imp1'),{edits:arrayUnion(LV('ad26'))}), true);
await t('admin changes it again (another appended edit)', updateDoc(OD(ad,'imp1'),{edits:arrayUnion(LV('ad26',{level:'JV',at:2}))}), true);
await t('member cannot set a level', updateDoc(OD(mb,'imp1'),{edits:arrayUnion(LV('mb26',{at:3}))}), false);
await t('a level in another coach\'s name fails', updateDoc(OD(ad,'imp1'),{edits:arrayUnion(LV('mb26',{at:4}))}), false);
await t('a level edit cannot rewrite the results', updateDoc(OD(ad,'imp1'),{edits:arrayUnion(LV('ad26',{at:5})),results:[]}), false);
await t('earlier level edits cannot be removed', updateDoc(OD(ad,'imp1'),{edits:[LV('ad26',{at:6})]}), false);
console.log(`\n${n-bad}/${n} passed`); await env.cleanup(); process.exit(bad?1:0);
